### ISSUE TITLE
Can't find DangerFileScript in Kotlin Scripting

### ISSUE THREAD

**Issue by gulomov** [danger/kotlin#276]
Hello people, I am trying to activate the autocomplete, and after adding Script template classes and Script templates classpath 
![Screenshot 2024-04-12 at 13 19 34](https://github.com/danger/kotlin/assets/23394312/0a831d18-c022-4b8b-980c-360a6d113b9b)

I want to activate DangerFileScript but don't see it in Kotlin Scripting.

![Screenshot 2024-04-12 at 13 25 00](https://github.com/danger/kotlin/assets/23394312/fac4be95-0894-48df-933b-cf71d86bd473)

I see this cause of errors (Unresolved reference: danger) in my Dangerfile.df.kts

`import systems.danger.kotlin.*

danger(args) {

    onGitHub {

        // Big PR Check
        if ((pullRequest.additions ?: 0) - (pullRequest.deletions ?: 0) > 300) {
            warn("Big PR, try to keep changes smaller if you can")
        }

        // Work in progress check
        if (pullRequest.title.contains("WIP", false)) {
            warn("PR is classed as Work in Progress")
        }
    }
}`

**Comment by carlosesh** [comment]
I have the same issue

**Comment by efemoney** [comment]
Same issue, you can see what is wrong from the IDE logs
```
Caused by: kotlin.script.experimental.jvm.util.ClasspathExtractionException: Unable to get script compilation classpath from context, please specify explicit classpath via "kotlin.script.classpath" property
	at kotlin.script.experimental.jvm.util.JvmClasspathUtilKt.scriptCompilationClasspathFromContext(jvmClasspathUtil.kt:345)
	at kotlin.script.experimental.jvm.JvmScriptCompilationKt.dependenciesFromClassloader(jvmScriptCompilation.kt:57)
	at kotlin.script.experimental.jvm.JvmScriptCompilationKt.dependenciesFromClassloader$default(jvmScriptCompilation.kt:50)
	at kotlin.script.experimental.jvm.JvmScriptCompilationKt.dependenciesFromClassContext(jvmScriptCompilation.kt:39)
	at kotlin.script.experimental.jvm.JvmScriptCompilationKt.dependenciesFromClassContext$default(jvmScriptCompilation.kt:36)
	at systems.danger.kts.DangerFileScriptDefinition$1$1.invoke(DangerFileScriptDefinition.kt:37)
	at systems.danger.kts.DangerFileScriptDefinition$1$1.invoke(DangerFileScriptDefinition.kt:36)
	at kotlin.script.experimental.util.PropertiesCollection$Builder.invoke(propertiesCollection.kt:282)
	at systems.danger.kts.DangerFileScriptDefinition$1.invoke(DangerFileScriptDefinition.kt:36)
	at systems.danger.kts.DangerFileScriptDefinition$1.invoke(DangerFileScriptDefinition.kt:34)
	at kotlin.script.experimental.api.ScriptCompilationConfiguration.<init>(scriptCompilation.kt:23)
	at kotlin.script.experimental.api.ScriptCompilationConfiguration.<init>(scriptCompilation.kt:25)
	at systems.danger.kts.DangerFileScriptDefinition.<init>(DangerFileScriptDefinition.kt:33)
	at systems.danger.kts.DangerFileScriptDefinition.<clinit>(DangerFileScriptDefinition.kt)
```

**Comment by OptimumCode** [comment]
Hi, I had the same issue. Here is how I fixed that:

1. Do all the instructions from the main [README](https://github.com/danger/kotlin?tab=readme-ov-file#autocomplete-and-syntax-highlighting-in-intellij-idea-or-android-studio) file.
2. Go to `Main Manue` -> `Help` -> `Edit Custom Properties...`
3. Add the following line to the file (for macOs the path would probably be different but unfortunately I don't have macOs to provide an example. Probably, something like this `/opt/homebrew/Cellar/danger-kotlin/1.3.0/lib/danger/libs` based on the screenshot in the issue description):
   ```properties
   kotlin.script.classpath=/usr/local/lib/danger/libs
   ```
4. Restart your IDE

After that, you should see the DangerFileScript in `Kotlin scripting` menu.
![image](https://github.com/danger/kotlin/assets/23560203/549ba4c9-599f-49ac-8536-b37087b6ac7c)

Hope it will help someone. Also, the instructions in the main README should probably be updated. I think many people have the same issue and might not use this project because of that

**Comment by ron-diesel** [comment]
> Hi, I had the same issue. Here is how I fixed that:
> 
> 1. Do all the instructions from the main [README](https://github.com/danger/kotlin?tab=readme-ov-file#autocomplete-and-syntax-highlighting-in-intellij-idea-or-android-studio) file.
> 2. Go to `Main Menu` -> `Help` -> `Edit Custom Properties...`
> 3. Add the following line to the file (for macOs the path would probably be different but unfortunately I don't have macOs to provide an example. Probably, something like this `/opt/homebrew/Cellar/danger-kotlin/1.3.0/lib/danger/libs` based on the screenshot in the issue description):
>    ```ini
>    kotlin.script.classpath=/usr/local/lib/danger/libs
>    ```
> 4. Restart your IDE
> 
> After that, you should see the DangerFileScript in `Kotlin scripting` menu. ![image](https://private-user-images.githubusercontent.com/23560203/341963726-549ba4c9-599f-49ac-8536-b37087b6ac7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjQ1MzgsIm5iZiI6MTcyNTk2NDIzOCwicGF0aCI6Ii8yMzU2MDIwMy8zNDE5NjM3MjYtNTQ5YmE0YzktNTk5Zi00OWFjLTg1MzYtYjM3MDg3YjZhYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDEwMzAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMzVmZjIxN2U0Y2NkZmVlNmY4ZDhjYjU3YjMyZjM2NWQyZTc3ODFkODQ1OWUwYjY5ZWNmYWVkMTU3ZjAzNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPOe_m02DNNl5cOWHlOasi_TXRDLnNUnS5s5R5_RDkg)
> 
> Hope it will help someone. Also, the instructions in the main README should probably be updated. I think many people have the same issue and might not use this project because of that

it didn't help, I suspect because I can't follow the first part of the instructions in the readme, since even the main menu of the new versions of Android Studio doesn't have the appropriate fields

**Comment by OptimumCode** [comment]
Hi, @ron-diesel. What do you see in kotlin section?

**Comment by ron-diesel** [comment]
> Hi, @ron-diesel. What do you see in kotlin section?

Hi
<img width="1276" alt="image" src="https://github.com/user-attachments/assets/fa89250b-4115-48b6-ab82-6967633b8ae5">

**Comment by ron-diesel** [comment]
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/b13332f3-c342-4dce-848f-e74a3ae5c2fc">

**Comment by OptimumCode** [comment]
Please, take a look at issue description. The screenshot from there should help you

**Comment by ron-diesel** [comment]
> Please, take a look at issue description. The screenshot from there should help you

So i need to add such setting as issue author?
<img width="728" alt="image" src="https://github.com/user-attachments/assets/cb69638f-a6ff-4f28-88d6-f10070ba8fe4">

**Comment by OptimumCode** [comment]
Yes, as far as I remember, I did the same. Can share with you my settings once I have access to my laptop

**Comment by OptimumCode** [comment]
But of course, the path will depend on your system

**Comment by ron-diesel** [comment]
IDE does not allow to apply this setting. Which version of AS do you use?

**Comment by OptimumCode** [comment]
Originally, I did it in IntelliJ IDEA. But I just tried it in the AS Koala and everything worked (after the AS restart)

<details><summary>Android Studio details</summary>

_**Android Studio Koala Feature Drop | 2024.1.2**_
_**Build #AI-241.18034.62.2412.12266719, built on August 23, 2024**_

</details>

**Comment by ron-diesel** [comment]
> Originally, I did it in IntelliJ IDEA. But I just tried it in AS Koala and everything worked (after the AS restart). I did not have any problems with applying those settings.
> 
> Android Studio details
> _**Android Studio Koala Feature Drop | 2024.1.2**_ _**Build #AI-241.18034.62.2412.12266719, built on August 23, 2024**_

Then please tell me where your path leads and what's in the libs folder. In my case there is no libs folder, there is only /opt/homebrew/opt/danger-kotlin/lib/danger/danger-kotlin.jar

**Comment by ron-diesel** [comment]
I figured it out, it seems the problem is [this](https://issuetracker.google.com/issues/336007390)

**Comment by pablobaldez** [comment]
is there any workaround for this issue?

**Comment by ron-diesel** [comment]
@pablobaldez 
I created an empty Kotlin project, added this `dependencies {
    implementation "org.jetbrains.kotlin:kotlin-script-runtime:1.8.22"
    implementation files('/opt/homebrew/opt/danger-kotlin/lib/danger/danger-kotlin.jar')
}` to build.gradle, put the danger file into the `src/main/kotlin` and edited it with syntax highlighting, then manually transferred the finished script to the main project. There is also an option to wait until this is fixed in Android Studio

**Comment by OptimumCode** [comment]
Hi, @pablobaldez. Maybe you can try IntelliJ IDEA instead of Android Studio (if you are okay with switching between IDEs of course). I did not observe any issues with IDEA

**Comment by pablobaldez** [comment]
@OptimumCode I tried the community IntelliJ but then another problem appeared.
I made the `DangerFileScript` appears in the Kotlin Scritp list (only after changing `idea.properties` file)
But the references still not found.
Restarting the IDE didn't work

<img width="600" alt="Screenshot 2024-09-11 at 14 01 24" src="https://github.com/user-attachments/assets/6b681b49-9abd-43f2-af65-8118ae66a04e">

<img width="811" alt="Screenshot 2024-09-11 at 14 02 58" src="https://github.com/user-attachments/assets/9034fa3b-7a50-4cd8-8957-d7e3dd5bf99a">

**Comment by OptimumCode** [comment]
@pablobaldez Unfortunately, I am using Linux not a Mac so I cannot even try to reproduce the problem. However, you probably can find some useful information about the problem's cause in IDE logs. If you are using ToolBox you can click `Show log files`
![image](https://github.com/user-attachments/assets/c60c2126-6b59-481d-8d2d-1f1da29e4361)

and look for `idea.log` file. Otherwise, you need to go to `Menu > Help > Show logs` in IDE itself (more [here](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files))
